### ISSUE TITLE
First Frame is Off when baking alembic

### ISSUE THREAD

**Issue by croustimsh** [sharpen3d/openvat#9]
In blender, I am using Alembic to bake multiples assets into one single animated objet.
I then use this object to bake the animation using OpenVat. 
Sadly the first frame is off. the mesh is offset in space ( seems to be by the x,y,z amount).
I wonder if the baking process take place before the first frame of the alembic file is processed.

![Image](https://github.com/user-attachments/assets/a580126b-b354-4bfd-9163-416eb8b0c69a)

**Comment by Dundan17** [comment]
Same problem here. Everything works fine except the animation starts offset. It happens when I use OpenVat on a rigged object.

**Comment by Dundan17** [comment]
I solved my problem. I was using the addon on my mac. When i tried it on windows everything worked fine. No offset.

**Comment by croustimsh** [comment]
I'm on windows sadly :(

**Comment by sharpen3d** [comment]
Weird, sorry I've been slacking on responses, real job is taking over a lot of my time for this stuff. Maybe worth noting it is always set to start at frame 1, not frame 0. - I've been meaning to update this to a custom range for quite a while.

@croustimsh if you upload your file I'll take a look

I've also had success in weird circumstances by setting up a geometry node group to realize a collection, and bake that object referencing a collection of objects rather than baking the target object itself (probably need to put a demo together to actually explain this method in detail.)

**Comment by sharpen3d** [comment]
This issue is fixed in my working update, will be added here before submitting to Blender for approval. Also added arbitrary frame range. Need to do a few more tests, but should be released in the next couple days.

**Comment by sharpen3d** [comment]
This issue should be fixed with 1.0.3 (currently in preview)

**Comment by croustimsh** [comment]
Thank you, I'll check it but I have found a work around in the meantime.
I will definitely update for my futures animations

**Comment by pookzzz** [comment]
> Thank you, I'll check it but I have found a work around in the meantime. I will definitely update for my futures animations

Do you mind sharing your work around? I still encounter the offset issue on the first frame

<img width="644" alt="Image" src="https://github.com/user-attachments/assets/f3f32eb4-3c0c-48d6-8e22-3d36b02610a4" />
